// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AILabTools.Generated.Params;
using AILabTools.Generated.Responses;
using AILabTools.Http;

namespace AILabTools.Api;

/// <summary>AILabTools common API methods.</summary>
public sealed class CommonApi
{
    private readonly Requester _requester;

    internal CommonApi(Requester requester)
    {
        _requester = requester;
    }

    public Task<CommonQueryAsyncTaskResultResponse> CommonQueryAsyncTaskResultAsync(
        CommonQueryAsyncTaskResultParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CommonQueryAsyncTaskResultResponse>(
            HttpMethod.Get, "/api/common/query-async-task-result", parameters, false, cancellationToken);
    }

    public Task<CommonQueryCreditsResponse> CommonQueryCreditsAsync(
        CommonQueryCreditsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CommonQueryCreditsResponse>(
            HttpMethod.Get, "/api/common/query-credits", parameters, false, cancellationToken);
    }

}
