// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AILabTools.Generated.Params;
using AILabTools.Generated.Responses;
using AILabTools.Http;

namespace AILabTools.Api;

/// <summary>AILabTools cutout API methods.</summary>
public sealed class CutoutApi
{
    private readonly Requester _requester;

    internal CutoutApi(Requester requester)
    {
        _requester = requester;
    }

    public Task<CutoutClothingBackgroundRemovalResponse> CutoutClothingBackgroundRemovalAsync(
        CutoutClothingBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutClothingBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/general/apparel-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutProductBackgroundRemovalResponse> CutoutProductBackgroundRemovalAsync(
        CutoutProductBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutProductBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/general/commodity-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutFoodBackgroundRemovalResponse> CutoutFoodBackgroundRemovalAsync(
        CutoutFoodBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutFoodBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/general/food-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutUniversalBackgroundRemovalResponse> CutoutUniversalBackgroundRemovalAsync(
        CutoutUniversalBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutUniversalBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/general/universal-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutAvatarExtractionResponse> CutoutAvatarExtractionAsync(
        CutoutAvatarExtractionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutAvatarExtractionResponse>(
            HttpMethod.Post, "/api/cutout/portrait/avatar-extraction", parameters, true, cancellationToken);
    }

    public Task<CutoutHairExtractionResponse> CutoutHairExtractionAsync(
        CutoutHairExtractionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutHairExtractionResponse>(
            HttpMethod.Post, "/api/cutout/portrait/hairstyle-extraction", parameters, true, cancellationToken);
    }

    public Task<CutoutHumanBackgroundRemovalResponse> CutoutHumanBackgroundRemovalAsync(
        CutoutHumanBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutHumanBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/portrait/portrait-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutHDUniversalBackgroundRemovalResponse> CutoutHDUniversalBackgroundRemovalAsync(
        CutoutHDUniversalBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutHDUniversalBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/general/hd-universal-background-removal", parameters, true, cancellationToken);
    }

    public Task<CutoutHdHumanBodyBackgroundRemovalResponse> CutoutHdHumanBodyBackgroundRemovalAsync(
        CutoutHdHumanBodyBackgroundRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<CutoutHdHumanBodyBackgroundRemovalResponse>(
            HttpMethod.Post, "/api/cutout/portrait/hd-portrait-background-removal", parameters, true, cancellationToken);
    }

}
