// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AILabTools.Generated.Params;
using AILabTools.Generated.Responses;
using AILabTools.Http;

namespace AILabTools.Api;

/// <summary>AILabTools image API methods.</summary>
public sealed class ImageApi
{
    private readonly Requester _requester;

    internal ImageApi(Requester requester)
    {
        _requester = requester;
    }

    public Task<ImageQueryingAsyncTaskResultsResponse> ImageQueryingAsyncTaskResultsAsync(
        ImageQueryingAsyncTaskResultsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageQueryingAsyncTaskResultsResponse>(
            HttpMethod.Get, "/api/image/asyn-task-results", parameters, false, cancellationToken);
    }

    public Task<ImageAiImageExtenderResponse> ImageAiImageExtenderAsync(
        ImageAiImageExtenderParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAiImageExtenderResponse>(
            HttpMethod.Post, "/api/image/editing/ai-image-extender", parameters, true, cancellationToken);
    }

    public Task<ImageAiObjectReplacerResponse> ImageAiObjectReplacerAsync(
        ImageAiObjectReplacerParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAiObjectReplacerResponse>(
            HttpMethod.Post, "/api/image/editing/ai-object-replacer", parameters, true, cancellationToken);
    }

    public Task<ImageAIImageCroppingResponse> ImageAIImageCroppingAsync(
        ImageAIImageCroppingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAIImageCroppingResponse>(
            HttpMethod.Post, "/api/image/editing/image-cropping", parameters, true, cancellationToken);
    }

    public Task<ImageErasureResponse> ImageErasureAsync(
        ImageErasureParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageErasureResponse>(
            HttpMethod.Post, "/api/image/editing/image-erase", parameters, true, cancellationToken);
    }

    public Task<ImageInvisibleImageWatermarkResponse> ImageInvisibleImageWatermarkAsync(
        ImageInvisibleImageWatermarkParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageInvisibleImageWatermarkResponse>(
            HttpMethod.Post, "/api/image/editing/image-invisible-image-watermark", parameters, true, cancellationToken);
    }

    public Task<ImageInvisibleTextWatermarkResponse> ImageInvisibleTextWatermarkAsync(
        ImageInvisibleTextWatermarkParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageInvisibleTextWatermarkResponse>(
            HttpMethod.Post, "/api/image/editing/image-invisible-text-watermarking", parameters, true, cancellationToken);
    }

    public Task<ImageIntelligentCompositionResponse> ImageIntelligentCompositionAsync(
        ImageIntelligentCompositionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageIntelligentCompositionResponse>(
            HttpMethod.Post, "/api/image/editing/intelligent-composition", parameters, true, cancellationToken);
    }

    public Task<ImagePhotoEditingResponse> ImagePhotoEditingAsync(
        ImagePhotoEditingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImagePhotoEditingResponse>(
            HttpMethod.Post, "/api/image/editing/photo-retouching", parameters, true, cancellationToken);
    }

    public Task<ImageRemoveObjectsResponse> ImageRemoveObjectsAsync(
        ImageRemoveObjectsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageRemoveObjectsResponse>(
            HttpMethod.Post, "/api/image/editing/remove-objects", parameters, true, cancellationToken);
    }

    public Task<ImageRemoveObjectsResponse> RemoveObjectsAsync(
        ImageRemoveObjectsParams parameters,
        CancellationToken cancellationToken = default)
        => ImageRemoveObjectsAsync(parameters, cancellationToken);

    public Task<ImageRemoveObjectsAdvancedResponse> ImageRemoveObjectsAdvancedAsync(
        ImageRemoveObjectsAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageRemoveObjectsAdvancedResponse>(
            HttpMethod.Post, "/api/image/editing/remove-objects-advanced", parameters, true, cancellationToken);
    }

    public Task<ImageRemoveObjectsProResponse> ImageRemoveObjectsProAsync(
        ImageRemoveObjectsProParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageRemoveObjectsProResponse>(
            HttpMethod.Post, "/api/image/editing/remove-objects-pro", parameters, true, cancellationToken);
    }

    public Task<ImageAICartoonGeneratorResponse> ImageAICartoonGeneratorAsync(
        ImageAICartoonGeneratorParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAICartoonGeneratorResponse>(
            HttpMethod.Post, "/api/image/effects/ai-anime-generator", parameters, true, cancellationToken);
    }

    public Task<ImageColoringResponse> ImageColoringAsync(
        ImageColoringParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageColoringResponse>(
            HttpMethod.Post, "/api/image/effects/image-colorization", parameters, true, cancellationToken);
    }

    public Task<ImageStyleTransferResponse> ImageStyleTransferAsync(
        ImageStyleTransferParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageStyleTransferResponse>(
            HttpMethod.Post, "/api/image/effects/image-style-conversion", parameters, true, cancellationToken);
    }

    public Task<ImageStyleMigrationResponse> ImageStyleMigrationAsync(
        ImageStyleMigrationParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageStyleMigrationResponse>(
            HttpMethod.Post, "/api/image/effects/image-style-migration", parameters, true, cancellationToken);
    }

    public Task<ImageColorEnhancementResponse> ImageColorEnhancementAsync(
        ImageColorEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageColorEnhancementResponse>(
            HttpMethod.Post, "/api/image/enhance/image-color-enhancement", parameters, true, cancellationToken);
    }

    public Task<ImageContrastEnhancementResponse> ImageContrastEnhancementAsync(
        ImageContrastEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageContrastEnhancementResponse>(
            HttpMethod.Post, "/api/image/enhance/image-contrast-enhancement", parameters, true, cancellationToken);
    }

    public Task<ImageDehazeResponse> ImageDehazeAsync(
        ImageDehazeParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageDehazeResponse>(
            HttpMethod.Post, "/api/image/enhance/image-defogging", parameters, true, cancellationToken);
    }

    public Task<ImageLosslessEnlargementResponse> ImageLosslessEnlargementAsync(
        ImageLosslessEnlargementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageLosslessEnlargementResponse>(
            HttpMethod.Post, "/api/image/enhance/image-lossless-enlargement", parameters, true, cancellationToken);
    }

    public Task<ImageLosslessEnlargementResponse> UpscaleAsync(
        ImageLosslessEnlargementParams parameters,
        CancellationToken cancellationToken = default)
        => ImageLosslessEnlargementAsync(parameters, cancellationToken);

    public Task<ImageClarityEnhancementResponse> ImageClarityEnhancementAsync(
        ImageClarityEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageClarityEnhancementResponse>(
            HttpMethod.Post, "/api/image/enhance/image-sharpness-enhancement", parameters, true, cancellationToken);
    }

    public Task<ImageDistortionCorrectionResponse> ImageDistortionCorrectionAsync(
        ImageDistortionCorrectionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageDistortionCorrectionResponse>(
            HttpMethod.Post, "/api/image/enhance/stretch-image-recovery", parameters, true, cancellationToken);
    }

    public Task<ImageCompositionAestheticsScoreResponse> ImageCompositionAestheticsScoreAsync(
        ImageCompositionAestheticsScoreParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageCompositionAestheticsScoreResponse>(
            HttpMethod.Post, "/api/image/rating/image-composition-aesthetics-scoring", parameters, true, cancellationToken);
    }

    public Task<ImageExposureRatingResponse> ImageExposureRatingAsync(
        ImageExposureRatingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageExposureRatingResponse>(
            HttpMethod.Post, "/api/image/rating/image-exposure-score", parameters, true, cancellationToken);
    }

    public Task<ImageAINailArtResponse> ImageAINailArtAsync(
        ImageAINailArtParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAINailArtResponse>(
            HttpMethod.Post, "/api/image/editing/ai-nail-art", parameters, true, cancellationToken);
    }

    public Task<ImageAINailArtProResponse> ImageAINailArtProAsync(
        ImageAINailArtProParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAINailArtProResponse>(
            HttpMethod.Post, "/api/image/editing/ai-nail-art-pro", parameters, true, cancellationToken);
    }

    public Task<ImageAIPhotographyResponse> ImageAIPhotographyAsync(
        ImageAIPhotographyParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAIPhotographyResponse>(
            HttpMethod.Post, "/api/image/effects/ai-photography", parameters, true, cancellationToken);
    }

    public Task<ImageAIEmojiGeneratorResponse> ImageAIEmojiGeneratorAsync(
        ImageAIEmojiGeneratorParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAIEmojiGeneratorResponse>(
            HttpMethod.Post, "/api/image/effects/photo-to-emoji-grid", parameters, true, cancellationToken);
    }

    public Task<ImagePhotoToColoringPageResponse> ImagePhotoToColoringPageAsync(
        ImagePhotoToColoringPageParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImagePhotoToColoringPageResponse>(
            HttpMethod.Post, "/api/image/effects/photo-to-line-art", parameters, true, cancellationToken);
    }

    public Task<ImageAIFlowerWallpaperResponse> ImageAIFlowerWallpaperAsync(
        ImageAIFlowerWallpaperParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<ImageAIFlowerWallpaperResponse>(
            HttpMethod.Post, "/api/image/generation/ai-flower-wallpaper", parameters, true, cancellationToken);
    }

}
