// <auto-generated />
#nullable enable
using System;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;
using AILabTools.Generated.Params;
using AILabTools.Generated.Responses;
using AILabTools.Http;

namespace AILabTools.Api;

/// <summary>AILabTools portrait API methods.</summary>
public sealed class PortraitApi
{
    private readonly Requester _requester;

    internal PortraitApi(Requester requester)
    {
        _requester = requester;
    }

    public Task<PortraitFaceAnalyzerResponse> PortraitFaceAnalyzerAsync(
        PortraitFaceAnalyzerParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFaceAnalyzerResponse>(
            HttpMethod.Post, "/api/portrait/analysis/face-analyzer", parameters, true, cancellationToken);
    }

    public Task<PortraitFaceAnalyzerAdvancedResponse> PortraitFaceAnalyzerAdvancedAsync(
        PortraitFaceAnalyzerAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFaceAnalyzerAdvancedResponse>(
            HttpMethod.Post, "/api/portrait/analysis/face-analyzer-advanced", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialLandmarksResponse> PortraitFacialLandmarksAsync(
        PortraitFacialLandmarksParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialLandmarksResponse>(
            HttpMethod.Post, "/api/portrait/analysis/face-key-points", parameters, true, cancellationToken);
    }

    public Task<PortraitSkinAnalysisBasicResponse> PortraitSkinAnalysisBasicAsync(
        PortraitSkinAnalysisBasicParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitSkinAnalysisBasicResponse>(
            HttpMethod.Post, "/api/portrait/analysis/skin-analysis", parameters, true, cancellationToken);
    }

    public Task<PortraitSkinAnalysisAdvancedResponse> PortraitSkinAnalysisAdvancedAsync(
        PortraitSkinAnalysisAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitSkinAnalysisAdvancedResponse>(
            HttpMethod.Post, "/api/portrait/analysis/skin-analysis-advanced", parameters, true, cancellationToken);
    }

    public Task<PortraitSkinAnalysisProfessionalResponse> PortraitSkinAnalysisProfessionalAsync(
        PortraitSkinAnalysisProfessionalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitSkinAnalysisProfessionalResponse>(
            HttpMethod.Post, "/api/portrait/analysis/skin-analysis-pro", parameters, true, cancellationToken);
    }

    public Task<PortraitSkinDiseaseDetectionResponse> PortraitSkinDiseaseDetectionAsync(
        PortraitSkinDiseaseDetectionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitSkinDiseaseDetectionResponse>(
            HttpMethod.Post, "/api/portrait/analysis/skin-disease-detection", parameters, true, cancellationToken);
    }

    public Task<PortraitTryOnClothesResponse> PortraitTryOnClothesAsync(
        PortraitTryOnClothesParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitTryOnClothesResponse>(
            HttpMethod.Post, "/api/portrait/editing/try-on-clothes", parameters, true, cancellationToken);
    }

    public Task<PortraitTryOnClothesProResponse> PortraitTryOnClothesProAsync(
        PortraitTryOnClothesProParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitTryOnClothesProResponse>(
            HttpMethod.Post, "/api/portrait/editing/try-on-clothes-pro", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialBlurringResponse> PortraitFacialBlurringAsync(
        PortraitFacialBlurringParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialBlurringResponse>(
            HttpMethod.Post, "/api/portrait/effects/blurred-faces", parameters, true, cancellationToken);
    }

    public Task<PortraitExpressionEditingResponse> PortraitExpressionEditingAsync(
        PortraitExpressionEditingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitExpressionEditingResponse>(
            HttpMethod.Post, "/api/portrait/effects/emotion-editor", parameters, true, cancellationToken);
    }

    public Task<PortraitFaceRestorationEnhancementResponse> PortraitFaceRestorationEnhancementAsync(
        PortraitFaceRestorationEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFaceRestorationEnhancementResponse>(
            HttpMethod.Post, "/api/portrait/effects/enhance-face", parameters, true, cancellationToken);
    }

    public Task<PortraitFaceAttributeEditingResponse> PortraitFaceAttributeEditingAsync(
        PortraitFaceAttributeEditingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFaceAttributeEditingResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-attribute-editing", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialBeautificationResponse> PortraitFacialBeautificationAsync(
        PortraitFacialBeautificationParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialBeautificationResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-beauty", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialBeautificationAdvancedResponse> PortraitFacialBeautificationAdvancedAsync(
        PortraitFacialBeautificationAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialBeautificationAdvancedResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-beauty-advanced", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialBeautificationProResponse> PortraitFacialBeautificationProAsync(
        PortraitFacialBeautificationProParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialBeautificationProResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-beauty-pro", parameters, true, cancellationToken);
    }

    public Task<PortraitFacialFiltersResponse> PortraitFacialFiltersAsync(
        PortraitFacialFiltersParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFacialFiltersResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-filter", parameters, true, cancellationToken);
    }

    public Task<PortraitFaceFusionResponse> PortraitFaceFusionAsync(
        PortraitFaceFusionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitFaceFusionResponse>(
            HttpMethod.Post, "/api/portrait/effects/face-fusion", parameters, true, cancellationToken);
    }

    public Task<PortraitHairstyleEditingResponse> PortraitHairstyleEditingAsync(
        PortraitHairstyleEditingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitHairstyleEditingResponse>(
            HttpMethod.Post, "/api/portrait/effects/hairstyle-editor", parameters, true, cancellationToken);
    }

    public Task<PortraitHairstyleEditingProResponse> PortraitHairstyleEditingProAsync(
        PortraitHairstyleEditingProParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitHairstyleEditingProResponse>(
            HttpMethod.Post, "/api/portrait/effects/hairstyle-editor-pro", parameters, true, cancellationToken);
    }

    public Task<PortraitHairstyleEditingProResponse> ChangeHairstyleAsync(
        PortraitHairstyleEditingProParams parameters,
        CancellationToken cancellationToken = default)
        => PortraitHairstyleEditingProAsync(parameters, cancellationToken);

    public Task<PortraitLipsColorChangerResponse> PortraitLipsColorChangerAsync(
        PortraitLipsColorChangerParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitLipsColorChangerResponse>(
            HttpMethod.Post, "/api/portrait/effects/lips-color-changer", parameters, true, cancellationToken);
    }

    public Task<PortraitLivePhotosResponse> PortraitLivePhotosAsync(
        PortraitLivePhotosParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitLivePhotosResponse>(
            HttpMethod.Post, "/api/portrait/effects/live-photo", parameters, true, cancellationToken);
    }

    public Task<PortraitCartoonYourselfResponse> PortraitCartoonYourselfAsync(
        PortraitCartoonYourselfParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitCartoonYourselfResponse>(
            HttpMethod.Post, "/api/portrait/effects/portrait-animation", parameters, true, cancellationToken);
    }

    public Task<PortraitIntelligentBeautificationResponse> PortraitIntelligentBeautificationAsync(
        PortraitIntelligentBeautificationParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitIntelligentBeautificationResponse>(
            HttpMethod.Post, "/api/portrait/effects/smart-beauty", parameters, true, cancellationToken);
    }

    public Task<PortraitIntelligentBeautificationResponse> RetouchAsync(
        PortraitIntelligentBeautificationParams parameters,
        CancellationToken cancellationToken = default)
        => PortraitIntelligentBeautificationAsync(parameters, cancellationToken);

    public Task<PortraitIntelligentFaceSlimmingResponse> PortraitIntelligentFaceSlimmingAsync(
        PortraitIntelligentFaceSlimmingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitIntelligentFaceSlimmingResponse>(
            HttpMethod.Post, "/api/portrait/effects/smart-face-slimming", parameters, true, cancellationToken);
    }

    public Task<PortraitIntelligentSkinRetouchingResponse> PortraitIntelligentSkinRetouchingAsync(
        PortraitIntelligentSkinRetouchingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitIntelligentSkinRetouchingResponse>(
            HttpMethod.Post, "/api/portrait/effects/smart-skin", parameters, true, cancellationToken);
    }

    public Task<PortraitTryOnClothesRefinerResponse> PortraitTryOnClothesRefinerAsync(
        PortraitTryOnClothesRefinerParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitTryOnClothesRefinerResponse>(
            HttpMethod.Post, "/api/portrait/enhance/try-on-clothes-refiner", parameters, true, cancellationToken);
    }

    public Task<PortraitAIFaceRatingResponse> PortraitAIFaceRatingAsync(
        PortraitAIFaceRatingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIFaceRatingResponse>(
            HttpMethod.Post, "/api/portrait/analysis/ai-face-rating", parameters, true, cancellationToken);
    }

    public Task<PortraitAIBaldResponse> PortraitAIBaldAsync(
        PortraitAIBaldParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIBaldResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-bald", parameters, true, cancellationToken);
    }

    public Task<PortraitAIBeardRemovalResponse> PortraitAIBeardRemovalAsync(
        PortraitAIBeardRemovalParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIBeardRemovalResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-beard-removal", parameters, true, cancellationToken);
    }

    public Task<PortraitAIBeardStylingResponse> PortraitAIBeardStylingAsync(
        PortraitAIBeardStylingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIBeardStylingResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-beard-styling", parameters, true, cancellationToken);
    }

    public Task<PortraitAIBreastExpansionResponse> PortraitAIBreastExpansionAsync(
        PortraitAIBreastExpansionParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIBreastExpansionResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-big-tits", parameters, true, cancellationToken);
    }

    public Task<PortraitAIButtEnhancementResponse> PortraitAIButtEnhancementAsync(
        PortraitAIButtEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIButtEnhancementResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-butt-enhancement", parameters, true, cancellationToken);
    }

    public Task<PortraitAIColoredContactsResponse> PortraitAIColoredContactsAsync(
        PortraitAIColoredContactsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIColoredContactsResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-colored-contacts", parameters, true, cancellationToken);
    }

    public Task<PortraitAIEyebrowsResponse> PortraitAIEyebrowsAsync(
        PortraitAIEyebrowsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIEyebrowsResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-eyebrows", parameters, true, cancellationToken);
    }

    public Task<PortraitAIEyelashesResponse> PortraitAIEyelashesAsync(
        PortraitAIEyelashesParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIEyelashesResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-eyelashes", parameters, true, cancellationToken);
    }

    public Task<PortraitAIEyeshadowTryOnResponse> PortraitAIEyeshadowTryOnAsync(
        PortraitAIEyeshadowTryOnParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIEyeshadowTryOnResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-eyeshadow", parameters, true, cancellationToken);
    }

    public Task<PortraitAIFaceSwapResponse> PortraitAIFaceSwapAsync(
        PortraitAIFaceSwapParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIFaceSwapResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-face-swap", parameters, true, cancellationToken);
    }

    public Task<PortraitAIFatFilterResponse> PortraitAIFatFilterAsync(
        PortraitAIFatFilterParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIFatFilterResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-fat-filter", parameters, true, cancellationToken);
    }

    public Task<PortraitAIHairColorResponse> PortraitAIHairColorAsync(
        PortraitAIHairColorParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIHairColorResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-hair-color", parameters, true, cancellationToken);
    }

    public Task<PortraitAIHairLossSimulationResponse> PortraitAIHairLossSimulationAsync(
        PortraitAIHairLossSimulationParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIHairLossSimulationResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-hair-loss-simulation", parameters, true, cancellationToken);
    }

    public Task<PortraitAILipEnhancementResponse> PortraitAILipEnhancementAsync(
        PortraitAILipEnhancementParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAILipEnhancementResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-lip-enhancement", parameters, true, cancellationToken);
    }

    public Task<PortraitAIWaistSlimmingResponse> PortraitAIWaistSlimmingAsync(
        PortraitAIWaistSlimmingParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIWaistSlimmingResponse>(
            HttpMethod.Post, "/api/portrait/editing/ai-waist-slimming", parameters, true, cancellationToken);
    }

    public Task<PortraitTryOnClothesPremiumResponse> PortraitTryOnClothesPremiumAsync(
        PortraitTryOnClothesPremiumParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitTryOnClothesPremiumResponse>(
            HttpMethod.Post, "/api/portrait/editing/try-on-clothes-premium", parameters, true, cancellationToken);
    }

    public Task<PortraitAIBigHeadEffectResponse> PortraitAIBigHeadEffectAsync(
        PortraitAIBigHeadEffectParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIBigHeadEffectResponse>(
            HttpMethod.Post, "/api/portrait/effects/ai-big-head-effect", parameters, true, cancellationToken);
    }

    public Task<PortraitAIHalloweenMaskResponse> PortraitAIHalloweenMaskAsync(
        PortraitAIHalloweenMaskParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIHalloweenMaskResponse>(
            HttpMethod.Post, "/api/portrait/effects/ai-halloween-mask", parameters, true, cancellationToken);
    }

    public Task<PortraitAILipBiteExpressionsResponse> PortraitAILipBiteExpressionsAsync(
        PortraitAILipBiteExpressionsParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAILipBiteExpressionsResponse>(
            HttpMethod.Post, "/api/portrait/effects/ai-lip-bite-expressions", parameters, true, cancellationToken);
    }

    public Task<PortraitAIRedLipGlossResponse> PortraitAIRedLipGlossAsync(
        PortraitAIRedLipGlossParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAIRedLipGlossResponse>(
            HttpMethod.Post, "/api/portrait/effects/ai-red-lip-gloss", parameters, true, cancellationToken);
    }

    public Task<PortraitAISquareFaceFilterResponse> PortraitAISquareFaceFilterAsync(
        PortraitAISquareFaceFilterParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAISquareFaceFilterResponse>(
            HttpMethod.Post, "/api/portrait/effects/ai-square-face-filter", parameters, true, cancellationToken);
    }

    public Task<PortraitExpressionEditingAdvancedResponse> PortraitExpressionEditingAdvancedAsync(
        PortraitExpressionEditingAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitExpressionEditingAdvancedResponse>(
            HttpMethod.Post, "/api/portrait/effects/emotion-editor-advanced", parameters, true, cancellationToken);
    }

    public Task<PortraitHairstyleEditingPremiumResponse> PortraitHairstyleEditingPremiumAsync(
        PortraitHairstyleEditingPremiumParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitHairstyleEditingPremiumResponse>(
            HttpMethod.Post, "/api/portrait/effects/hairstyle-editor-premium", parameters, true, cancellationToken);
    }

    public Task<PortraitAISkinEnhancementAdvancedResponse> PortraitAISkinEnhancementAdvancedAsync(
        PortraitAISkinEnhancementAdvancedParams parameters,
        CancellationToken cancellationToken = default)
    {
        if (parameters == null) throw new ArgumentNullException(nameof(parameters));
        return _requester.RequestAsync<PortraitAISkinEnhancementAdvancedResponse>(
            HttpMethod.Post, "/api/portrait/effects/smart-skin-advanced", parameters, true, cancellationToken);
    }

}
